# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 16:03


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('t_time', models.CharField(blank=True, max_length=64)),
                ('published', models.DateTimeField(blank=True, default=None, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
