# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 14:38


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name=b'First name')),
                ('last_name', models.CharField(max_length=50, verbose_name=b'Last name')),
                ('email', models.EmailField(max_length=75, unique=True, verbose_name=b'E-mail address')),
            ],
        ),
    ]
