# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-27 15:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_ruleeventtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-date']},
        ),
    ]
