# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20170903_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u4e8b\u4ef6')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.Exercise')),
            ],
        ),
        migrations.AlterField(
            model_name='ruleeventtemplate',
            name='rule',
            field=models.CharField(choices=[(b'first_20_days', b'first_20_days'), (b'not_first_20_days', b'not_first_20_days'), (b'last_trading_day', b'last_trading_day'), (b'last_sunday', b'last_sunday')], max_length=64),
        ),
    ]
