# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 01:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20170912_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='montheventtemplate',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='ruleeventtemplate',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='weekdayeventtemplate',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
