# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20170913_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mandatory',
            field=models.BooleanField(default=False, help_text='\u8fc7\u53bb\u672a\u5b8c\u6210\u7684mandatory\u4efb\u52a1\u4f1a\u7ee7\u7eed\u663e\u793a\u5728\u4eca\u65e5\u4efb\u52a1\u91cc\u3002', verbose_name='\u5fc5\u987b\u5b8c\u6210?'),
        ),
        migrations.AddField(
            model_name='montheventtemplate',
            name='mandatory',
            field=models.BooleanField(default=False, help_text='\u8fc7\u53bb\u672a\u5b8c\u6210\u7684mandatory\u4efb\u52a1\u4f1a\u7ee7\u7eed\u663e\u793a\u5728\u4eca\u65e5\u4efb\u52a1\u91cc\u3002', verbose_name='\u5fc5\u987b\u5b8c\u6210?'),
        ),
        migrations.AddField(
            model_name='ruleeventtemplate',
            name='mandatory',
            field=models.BooleanField(default=False, help_text='\u8fc7\u53bb\u672a\u5b8c\u6210\u7684mandatory\u4efb\u52a1\u4f1a\u7ee7\u7eed\u663e\u793a\u5728\u4eca\u65e5\u4efb\u52a1\u91cc\u3002', verbose_name='\u5fc5\u987b\u5b8c\u6210?'),
        ),
        migrations.AddField(
            model_name='weekdayeventtemplate',
            name='mandatory',
            field=models.BooleanField(default=False, help_text='\u8fc7\u53bb\u672a\u5b8c\u6210\u7684mandatory\u4efb\u52a1\u4f1a\u7ee7\u7eed\u663e\u793a\u5728\u4eca\u65e5\u4efb\u52a1\u91cc\u3002', verbose_name='\u5fc5\u987b\u5b8c\u6210?'),
        ),
    ]
