# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-07 15:08
from __future__ import unicode_literals

import diary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_auto_20170925_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryAudio',
            fields=[
                ('diarycontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diary.DiaryContent')),
                ('audio', models.FileField(upload_to=diary.models.get_diary_media_path)),
            ],
            bases=('diary.diarycontent',),
        ),
        migrations.AlterField(
            model_name='diaryimage',
            name='image',
            field=models.ImageField(upload_to=diary.models.get_diary_media_path),
        ),
    ]
