# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-07 16:39


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diary', '0012_auto_20171007_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='contenttypes.ContentType', blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='object_id',
            field=models.PositiveIntegerField(null=True, blank=True),
        ),
    ]
