# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 05:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_auto_20171008_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='events_generated',
            field=models.BooleanField(default=True),
        ),
    ]
