# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 06:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_auto_20171026_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Diaries'},
        ),
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
