# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 01:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_auto_20171026_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdayeventtemplate',
            name='weekdays',
            field=models.ManyToManyField(blank=True, to='diary.Weekday'),
        ),
    ]
