# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0017_auto_20171028_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='link_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='montheventtemplate',
            name='link_title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='montheventtemplate',
            name='link_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='ruleeventtemplate',
            name='link_title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ruleeventtemplate',
            name='link_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='weekdayeventtemplate',
            name='link_title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='weekdayeventtemplate',
            name='link_url',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
