# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-21 05:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_auto_20180114_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
