# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-26 15:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0020_annualeventtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualeventtemplate',
            name='month',
            field=models.CharField(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12')], max_length=2, verbose_name='\u6708'),
        ),
    ]
