# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-17 04:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0021_auto_20180426_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualeventtemplate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='montheventtemplate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruleeventtemplate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weekdayeventtemplate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
