# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-02 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0022_auto_20180717_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='done_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ruleeventtemplate',
            name='rule',
            field=models.CharField(
                choices=[(b'first_20_days', b'first_20_days'), (b'not_first_20_days', b'not_first_20_days'),
                         (b'last_trading_day', b'last_trading_day'), (b'last_sunday', b'last_sunday'),
                         (b'season_end', b'season_end')], max_length=64),
        ),
    ]
