# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-02 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0022_auto_20180717_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='done_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
