# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0023_event_done_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualeventtemplate',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='montheventtemplate',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruleeventtemplate',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weekdayeventtemplate',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
