# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='reverse_order',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5012\u5e8f\u6392\u5217?'),
        ),
    ]
