# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 05:55


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='tip',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.Category'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.Source'),
        ),
        migrations.AddField(
            model_name='longtip',
            name='tip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='long_tip', to='tips.Tip'),
        ),
    ]
