# Generated by Django 2.2.24 on 2021-07-25 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0023_auto_20210719_1017'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(unique=True)),
                ('initial_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='初始投资')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='现金')),
                ('initial_date', models.DateField(verbose_name='初始投资时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccountSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='时间')),
                ('net_asset', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='净资产')),
                ('stocks_asset', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='股票市值')),
                ('serial_number', models.PositiveIntegerField(null=True)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='现金')),
                ('increase', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='涨幅')),
                ('is_annual', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='user_stocks.UserAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccountStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='user_stocks.UserAccount')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.Stock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccountSnapshotStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('name', models.CharField(blank=True, max_length=16)),
                ('code', models.CharField(blank=True, max_length=6)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='总价')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='user_stocks.UserAccountSnapshot')),
                ('stock', models.ForeignKey(limit_choices_to={'star': True}, on_delete=django.db.models.deletion.PROTECT, to='stocks.Stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
