# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-16 08:26


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('directory', models.CharField(max_length=256)),
                ('analysed', models.BooleanField(default=False)),
                ('files_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=128)),
                ('ext', models.CharField(max_length=5)),
                ('size', models.IntegerField(null=True)),
                ('read', models.IntegerField(default=0)),
                ('ignored', models.BooleanField(default=False)),
                ('lines_count', models.IntegerField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='code_reading.Project')),
            ],
        ),
    ]
