# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='py_files_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='py_files_read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='py_lines_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='py_lines_read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
