# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-13 14:48


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=512)),
                ('order', models.IntegerField(default=1)),
                ('memo', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
