# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 17:11


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_collector', '0008_auto_20170314_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='\u6807\u9898')),
                ('original_url', models.CharField(blank=True, max_length=128, verbose_name='\u539f\u6587URL')),
                ('home', models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a\u5728\u4e3b\u9875')),
                ('note', models.TextField(blank=True, verbose_name='\u7b14\u8bb0')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_collector.Info')),
            ],
        ),
    ]
