# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65f6\u95f4')),
                ('serial_number', models.PositiveIntegerField(null=True)),
                ('net_asset', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='\u51c0\u8d44\u4ea7')),
                ('stocks_asset', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='\u80a1\u7968\u5e02\u503c')),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='\u73b0\u91d1')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u8d1f\u503a')),
                ('increase', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='\u6da8\u5e45')),
                ('has_transaction', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6709\u4ea4\u6613')),
                ('transactions_count', models.IntegerField(default=0)),
                ('error', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u8bef\u5dee')),
                ('comment', models.TextField(blank=True, default=b'', verbose_name='\u5907\u6ce8')),
                ('status_image', models.ImageField(blank=True, upload_to=b'snapshots')),
                ('change_image', models.ImageField(blank=True, upload_to=b'snapshots')),
                ('xueqiu_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('name', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=6)),
                ('amount', models.IntegerField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='\u603b\u4ef7')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.Snapshot')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='\u73b0\u91d1'),
        ),
        migrations.AlterField(
            model_name='pairtransaction',
            name='bought_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bought_pair_transactions', to='stocks.Stock', verbose_name='\u4e70\u5165\u80a1\u7968'),
        ),
        migrations.AlterField(
            model_name='pairtransaction',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stocks.StockPair'),
        ),
        migrations.AlterField(
            model_name='pairtransaction',
            name='sold_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_pair_transactions', to='stocks.Stock', verbose_name='\u5356\u51fa\u80a1\u7968'),
        ),
        migrations.AlterField(
            model_name='stockpair',
            name='started_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairs', to='stocks.Stock'),
        ),
        migrations.AlterField(
            model_name='stockpair',
            name='target_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targeted_pairs', to='stocks.Stock'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bought_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stocks.Stock', verbose_name='\u4e70\u5165\u80a1\u7968'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='stocks.Account'),
        ),
    ]
