# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20170320_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='BoughtSoldTransaction',
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='\u8d1f\u503a'),
        ),
        migrations.AlterField(
            model_name='snapshotstock',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='snapshotstock',
            name='name',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
