# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20170321_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=16, verbose_name='\u4ea4\u6613\u7c7b\u578b')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='\u4ea4\u6613\u4ef7\u683c')),
                ('amount', models.IntegerField(verbose_name='\u4ea4\u6613\u6570\u91cf')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='\u4ea4\u6613\u65f6\u95f4')),
                ('total_money', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='\u4ea4\u6613\u989d')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stocks.Account')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stocks.Stock', verbose_name='\u80a1\u7968')),
            ],
        ),
    ]
