# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairtransaction',
            name='bought_back_amount',
            field=models.IntegerField(blank=True, help_text='\u5b9e\u9645\u4e70\u56de\u7684\u6570\u91cf\u53ef\u80fd\u548c\u4e4b\u524d\u5356\u51fa\u7684\u6570\u91cf\u4e0d\u4e00\u81f4\uff0c\u8fd9\u4e2a\u503c\u7528\u4e8e\u663e\u793aTransaction\u7684\u4ea4\u6613\u989d\uff0c\u5e76\u4e0d\u7528\u4e8e\u8ba1\u7b97\u914d\u5bf9\u4ea4\u6613\u7684\u5229\u6da6\u3002', null=True, verbose_name='\u5b9e\u9645\u4e70\u56de\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(blank=True, choices=[('\u4e70\u5165', '\u4e70\u5165'), ('\u4e70\u5165', '\u5356\u51fa')], max_length=16, verbose_name='\u4ea4\u6613\u7c7b\u578b'),
        ),
    ]
