# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 10:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20170322_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtsoldtransaction',
            name='archived',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\xad\x98\xe6\xa1\xa3-\xe4\xb8\x8d\xe5\x86\x8d\xe8\xae\xa1\xe7\xae\x97\xe7\x9b\x88\xe4\xba\x8f'),
        ),
        migrations.AddField(
            model_name='pairtransaction',
            name='archived',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\xad\x98\xe6\xa1\xa3-\xe4\xb8\x8d\xe5\x86\x8d\xe8\xae\xa1\xe7\xae\x97\xe7\x9b\x88\xe4\xba\x8f'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(blank=True, choices=[('\u4e70\u5165', '\u4e70\u5165'), ('\u5356\u51fa', '\u5356\u51fa')], max_length=16, verbose_name='\u4ea4\u6613\u7c7b\u578b'),
        ),
    ]
