# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 09:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20170324_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtsoldtransaction',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='\u5b58\u6863-\u4e0d\u518d\u8ba1\u7b97\u76c8\u4e8f'),
        ),
        migrations.AlterField(
            model_name='pairtransaction',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='\u5b58\u6863-\u4e0d\u518d\u8ba1\u7b97\u76c8\u4e8f'),
        ),
    ]
