# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20170325_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtsoldtransaction',
            name='transactions',
            field=models.ManyToManyField(to='stocks.Transaction'),
        ),
        migrations.AddField(
            model_name='pairtransaction',
            name='transactions',
            field=models.ManyToManyField(to='stocks.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='has_updated_account',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7ecf\u66f4\u65b0\u8d26\u6237'),
        ),
    ]
