# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 06:58


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20170421_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='archive',
            new_name='watching',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='archived_reason',
        ),
    ]
