# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_auto_20170427_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tracking',
            field=models.BooleanField(default=False),
        ),
    ]
