# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_stock_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtsoldtransaction',
            name='transactions',
            field=models.ManyToManyField(editable=False, to='stocks.Transaction'),
        ),
        migrations.AlterField(
            model_name='pairtransaction',
            name='transactions',
            field=models.ManyToManyField(editable=False, to='stocks.Transaction'),
        ),
    ]
