# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 14:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_auto_20170714_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='is_annual',
            field=models.BooleanField(default=False),
        ),
    ]
