# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-29 08:15


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_snapshot_is_annual'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.IntegerField(default=100)),
                ('asset', models.PositiveIntegerField(default=0, verbose_name='\u8d44\u4ea7')),
                ('debt', models.PositiveIntegerField(default=0, verbose_name='\u8d1f\u503a')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Account')),
            ],
        ),
    ]
