# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-29 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_subaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='sub_accounts_asset',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, verbose_name='\u5b50\u8d26\u6237\u5e02\u503c'),
        ),
    ]
