# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-17 04:36


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_snapshot_sub_accounts_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subaccount',
            options={'ordering': ['order']},
        ),
    ]
