# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-15 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_accountstocksrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstocksrange',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_ranges', to='stocks.Account'),
        ),
    ]
