# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-09-08 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_auto_20200315_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtsoldtransaction',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=b'0.07', max_digits=6, verbose_name='\u5229\u7387\u6210\u672c'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_money',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='\u4ea4\u6613\u989d'),
        ),
    ]
