# Generated by Django 2.2.24 on 2021-07-19 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_auto_20200908_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstock',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='stocks.Account'),
        ),
        migrations.AlterField(
            model_name='accountstock',
            name='stock',
            field=models.ForeignKey(limit_choices_to={'star': True}, on_delete=django.db.models.deletion.PROTECT, to='stocks.Stock'),
        ),
        migrations.AlterField(
            model_name='accountstocksrange',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_ranges', to='stocks.Account'),
        ),
        migrations.AlterField(
            model_name='accountstocksrange',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=2, default='20', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='accountstocksrange',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=2, default='20', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='accountstocksrange',
            name='stocks',
            field=models.ManyToManyField(blank=True, limit_choices_to={'star': True}, null=True, to='stocks.Stock'),
        ),
        migrations.AlterField(
            model_name='boughtsoldtransaction',
            name='bought_stock',
            field=models.ForeignKey(limit_choices_to={'star': True}, on_delete=django.db.models.deletion.PROTECT, related_name='bs_transactions', to='stocks.Stock', verbose_name='买入股票'),
        ),
        migrations.AlterField(
            model_name='boughtsoldtransaction',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default='0.07', max_digits=6, verbose_name='利率成本'),
        ),
        migrations.AlterField(
            model_name='pairtransaction',
            name='bought_stock',
            field=models.ForeignKey(limit_choices_to={'star': True}, on_delete=django.db.models.deletion.PROTECT, related_name='bought_pair_transactions', to='stocks.Stock', verbose_name='买入股票'),
        ),
        migrations.AlterField(
            model_name='pairtransaction',
            name='pair',
            field=models.ForeignKey(blank=True, limit_choices_to={'star': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stocks.StockPair'),
        ),
        migrations.AlterField(
            model_name='pairtransaction',
            name='sold_stock',
            field=models.ForeignKey(limit_choices_to={'star': True}, on_delete=django.db.models.deletion.PROTECT, related_name='sold_pair_transactions', to='stocks.Stock', verbose_name='卖出股票'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='change_image',
            field=models.ImageField(blank=True, upload_to='snapshots'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='extra_content',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='更多内容'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='status_image',
            field=models.ImageField(blank=True, upload_to='snapshots'),
        ),
        migrations.AlterField(
            model_name='snapshotstock',
            name='stock',
            field=models.ForeignKey(limit_choices_to={'star': True}, on_delete=django.db.models.deletion.PROTECT, to='stocks.Stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='star',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tracking',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='watching',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='stockpair',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='stockpair',
            name='star',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='stockpair',
            name='started_stock',
            field=models.ForeignKey(limit_choices_to={'star': True}, on_delete=django.db.models.deletion.PROTECT, related_name='pairs', to='stocks.Stock'),
        ),
        migrations.AlterField(
            model_name='stockpair',
            name='target_stock',
            field=models.ForeignKey(limit_choices_to={'star': True}, on_delete=django.db.models.deletion.PROTECT, related_name='targeted_pairs', to='stocks.Stock'),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock',
            field=models.ForeignKey(limit_choices_to={'star': True}, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stocks.Stock', verbose_name='股票'),
        ),
    ]
