# Generated by Django 2.2.24 on 2021-09-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_auto_20210719_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStockGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('color', models.CharField(default='#FFFFFF', max_length=32)),
                ('order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=32, verbose_name='账户名称'),
        ),
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='账户网址'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='is_annual',
            field=models.BooleanField(default=False, verbose_name='是否是年度快照'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='serial_number',
            field=models.PositiveIntegerField(null=True, verbose_name='序号'),
        ),
        migrations.CreateModel(
            name='AccountStockGroupStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(blank=True, decimal_places=2, default='50', max_digits=5, null=True)),
                ('stock', models.ForeignKey(limit_choices_to={'star': True}, on_delete=django.db.models.deletion.PROTECT, to='stocks.Stock')),
                ('stock_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.AccountStockGroup')),
            ],
        ),
        migrations.AddField(
            model_name='accountstockgroup',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='stocks.Account'),
        ),
    ]
