# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 18:14


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_collector', '0002_info_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_collector.Content'),
        ),
        migrations.AlterField(
            model_name='infosource',
            name='interval',
            field=models.IntegerField(default=900, verbose_name='\u6293\u53d6\u95f4\u9694(\u79d2)'),
        ),
    ]
