# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_collector', '0003_auto_20170228_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='original_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
