# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_collector', '0004_auto_20170308_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
