# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:13


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_collector', '0006_auto_20170312_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('avatar_url', models.CharField(blank=True, max_length=1000)),
                ('raw', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_collector.Author'),
        ),
    ]
