# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 08:22


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_collector', '0007_auto_20170314_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info_collector.Author'),
        ),
    ]
