# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_collector', '0009_info_important'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['-important', '-timestamp']},
        ),
        migrations.AddField(
            model_name='info',
            name='tags',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
