# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 17:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_collector', '0011_infosource_silence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
