# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-05-02 07:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_collector', '0015_authorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_day_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='last_fetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='last_month_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='last_week_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='last_year_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='stop_fetching',
            field=models.BooleanField(default=False, verbose_name='\u505c\u6b62\u6293\u53d6'),
        ),
        migrations.AlterField(
            model_name='authorname',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
